# Generated by Django 3.0.14 on 2022-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=100)),
                ('Cat_img', models.ImageField(upload_to='Category_images/')),
            ],
        ),
    ]
