# Generated by Django 3.0.14 on 2022-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=50)),
                ('Brand_img', models.ImageField(upload_to='brand_imgs/')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
