# Generated by Django 3.0.14 on 2022-06-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20220620_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_title', models.CharField(max_length=250)),
                ('Product_img', models.ImageField(upload_to='Product_imgs/')),
                ('Product_desc', models.TextField()),
                ('Product_Price', models.PositiveIntegerField()),
                ('Product_Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Brand', verbose_name='Brand')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Category', verbose_name='Category')),
                ('Product_Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Color', verbose_name='Color')),
                ('Product_Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Size', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
