# Generated by Django 3.0.14 on 2022-06-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20220621_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_img', models.ImageField(upload_to='banner_imgs/')),
                ('Alt_txt', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'HomepageBanner',
                'verbose_name_plural': 'HomepageBanners',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Price',
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Products_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Price', models.PositiveIntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='Product')),
                ('Product_Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Color', verbose_name='Color')),
                ('Product_Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Size', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Products_Attribute',
                'verbose_name_plural': 'Products_Attributes',
            },
        ),
    ]
