# Generated by Django 3.0.14 on 2022-06-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20220621_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Attribute',
            new_name='ProductsAttribute',
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Category', verbose_name='Category'),
        ),
    ]
